name: PHP Composer and unittest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.2"
          - "8.3"

    steps:
    - uses: actions/checkout@v3

    - name: "Install PHP"
      uses: "shivammathur/setup-php@2.29.0"
      with:
        coverage: "none"
        php-version: "${{ matrix.php-version }}"
        ini-values: memory_limit=-1
        tools: composer:v2
      
    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: composer install --prefer-dist --no-interaction --no-progress

    - name: Run tests
      run: make phpunit
